### ISSUE TITLE
Unable to find root

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [mtb-tools/vscode-mono-workspace#2]
does not seem to work
![image](https://user-images.githubusercontent.com/86342787/196153015-224b9620-9b69-42ab-af02-a41548bcaf5c.png)

**Comment by melMass** [comment]
Hi, 

thanks for the report!

This is still a pre-release for now mainly because it's not well tested, especially on other OS than macOS.
I will address this pretty soon and do a "true" release later this week.

**Comment by melMass** [comment]
@sschneider-ihre-pvs Can you test again in 1.3.6? 
I was finally able to test it on all platforms

**Comment by sschneider-ihre-pvs** [comment]
Server returned 503

**Comment by sschneider-ihre-pvs** [comment]
![image](https://user-images.githubusercontent.com/86342787/196423531-bea24f2d-66a4-438f-9e25-8325509f878f.png)

**Comment by melMass** [comment]
Yes my bad, the fact that I unpublished it seems to make indexing take a lot longer it's up on the marketplace so it should not take that long now.

https://marketplace.visualstudio.com/items?itemName=melmass.vscode-mono-workspace

**Comment by melMass** [comment]
I think I fixed the issue in 1.4.0, my test sample had all cases (Cargo, nx, yarn) so I was not properly testing isolated cases.

Feel free to re-open if you still encounter it.
